[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["zhanglun <zhanglun1410@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "^1.1.0", features = ["sqlite"] }
dotenv = "0.9.0"